<a href="https://colab.research.google.com/github/minalagrawal2609/python/blob/main/NumpyTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY - 1 TASK OF NUMPY:-


In [ ]:
import numpy as np

In [ ]:
# Create a 1-D array of the numbers 1 to 10 using np.arange.
Numbers = np.arange(1, 11, 1)
print("Numbers:", Numbers)

Numbers: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Reshape it into a 2×5 matrix using .reshape(2, 5).
reshaping = Numbers.reshape(2, 5)
print(reshaping)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Print its .shape and .ndim and explain in your own words what each number means.
Shape_N = Numbers.shape
print("Shape:", Shape_N)

dimension_N = Numbers.ndim
print("Dimension:", dimension_N)

#AFTER RESHAPE THE ARRAY:-
print("After reshaping the array:")

Shape_r = reshaping.shape
print("Shape:", Shape_r)

dimension_r = reshaping.ndim
print("Dimension:", dimension_r)

Shape: (10,)
Dimension: 1
After reshaping the array:
Shape: (2, 5)
Dimension: 2


In [ ]:
# Create a 2-D array of shape (3, 3) containing the numbers 1–9 (hint: np.arange(1,10).reshape(3,3)).
array_2D = np.arange(1, 10, 1).reshape(3, 3)
print("array_2D:\n", array_2D)

array_2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Add the 1-D array [100, 200, 300] to it using broadcasting.
array_1D = np.array([100, 200, 300])
print("array_1D:", array_1D)
print()

print("After broadcasting:\n", array_2D + array_1D)

array_1D: [100 200 300]

After broadcasting:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [ ]:
# Compute the mean of each column (which axis do you need?).
print("Mean of array_2D:", array_2D.mean())
print("Mean of array_1D:", array_1D.mean())


Mean of array_2D: 5.0
Mean of array_1D: 200.0


DAY - 2 TASK OF NUMPY:-

In [ ]:
grid = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
print(grid)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
# From grid, select the middle row using slicing.
print("Middle row:", grid[1, :])

Middle row: [40 50 60]


In [ ]:
# From nums, create a boolean mask for numbers divisible by 7.
nums = np.array([4, 15, 8, 23, 42, 7, 16])

masks = nums % 7 == 0
print("Masks:", masks)
print()

# Use that mask to print only those numbers.
print("Only nums divisible by 7:", nums[masks])

Masks: [False False False False  True  True False]

Only nums divisible by 7: [42  7]


In [ ]:
# Create two 2×2 matrices C and D of your choice.
C = np.array([[2, 5],
              [7, 8]])
print("C:\n", C)
print()
D = np.array([[1, 9],
              [3, 4]])
print("D:\n", D)

C:
 [[2 5]
 [7 8]]

D:
 [[1 9]
 [3 4]]


In [ ]:
# Compute both C * D and C @ D, and print them next to each other. Confirm they differ.
print("Element-Wise(C * D):\n", C * D)
print("Matrix multiplicaton:\n", C @ D)


Element-Wise(C * D):
 [[ 2 45]
 [21 32]]
Matrix multiplicaton:
 [[17 38]
 [31 95]]


In [ ]:
# Find the inverse of C (check the determinant first — if it's 0, the inverse doesn't exist!).
Determinant_C = np.linalg.det(C)
print("Determinant_C:", Determinant_C)

C_inv = np.linalg.inv(C)
print("\nA inverse:\n", C_inv)
print("\nA @ A_inv (should be ~identity):\n", C @ C_inv)

Determinant_C: -18.999999999999996

A inverse:
 [[-0.42105263  0.26315789]
 [ 0.36842105 -0.10526316]]

A @ A_inv (should be ~identity):
 [[1. 0.]
 [0. 1.]]


Mini Capstone — Put Day 1 + Day 2 together

In [ ]:
# Scenario: You have exam scores for 5 students across 3 subjects.

# Create a (5, 3) array of random integer scores between 40 and 100 (hint: np.random.randint(40, 101, size=(5,3))).
Score = np.random.randint(40, 101, size=(5, 3))
print("Array:\n", Score)
print()

# Use an aggregation to find each student's average score (which axis?).
print("Average:", np.mean(Score))
print()

# Use boolean masking to find which scores are below 50.
mask = Score < 50
print("Masking:", Score[mask])
print()

# Add 5 bonus marks to every score using broadcasting.
add_bonus = ([[5]])
print("Add bonus:", Score + add_bonus)
print()

# Bonus: multiply the score matrix by a (3,) "weight" array (e.g. [0.5, 0.3, 0.2]) using @ to compute each student's weighted final score — a real matrix multiplication!
weight = np.array([0.5, 0.3, 0.2])

final_score = Score @ weight
print("Matrix multiplication:\n", final_score)


Array:
 [[52 91 53]
 [78 89 56]
 [81 99 81]
 [92 48 62]
 [41 58 42]]

Average: 68.2

Masking: [48 41 42]

Add bonus: [[ 57  96  58]
 [ 83  94  61]
 [ 86 104  86]
 [ 97  53  67]
 [ 46  63  47]]

Matrix multiplication:
 [63.9 76.9 86.4 72.8 46.3]
